export { TestappComponent } from "./testapp/testapp.component";
export { ChatboxComponent } from "./chatbox/chatbox.component";
export { HeaderComponent } from "./header/header.component";
export { DeznavComponent } from "./deznav/deznav.component";
export { NavheaderComponent } from "./navheader/navheader.component";
export { FooterComponent } from "./footer/footer.component";
// export { FruitproductsComponent } from "./fruitproducts/fruitproducts.component";
// export { FruitbannerComponent } from "./fruitbanner/fruitbanner.component";
// export { FruitbannerboxComponent } from "./fruitbannerbox/fruitbannerbox.component";
// export { FruitcestaComponent } from "./fruitcesta/fruitcesta.component";
// export { FruitfooterComponent } from "./fruitfooter/fruitfooter.component";
// export { FruittopbarComponent } from "./fruittopbar/fruittopbar.component";
// export { FruitcartComponent } from "./fruitcart/fruitcart.component";
// export { PagoComponent } from "./pago/pago.component";
